/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Order_Form;

import java.awt.event.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.*;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.*;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

    
/**
 *
 * @author Vageesha
 */

public class Order_Form extends javax.swing.JFrame {

    /**
     * Creates new form Order_Form
     */
    public Order_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Order_ID = new javax.swing.JLabel();
        Customer_ID = new javax.swing.JLabel();
        Product_ID = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        Order_Files = new javax.swing.JLabel();
        Order_Status = new javax.swing.JLabel();
        Discount = new javax.swing.JLabel();
        Total_Price = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Quantity_Input = new javax.swing.JTextField();
        DocumentListener documentListener = new DocumentListener() {
            public void changedUpdate(DocumentEvent documentEvent) {

            }
            public void insertUpdate(DocumentEvent documentEvent) {

                String qty = Quantity_Input.getText();
                String dis = Discount_Input.getText();
                String UnP = jLabel9.getText();
                Double UnPrice = Double.parseDouble(UnP);
                Double total = null;

                if((qty.equals("")) && (dis.equals("")))
                total = (Double) UnPrice;
                else if(dis.equals("")){
                    Integer qtyInt = Integer.parseInt(qty);
                    total = (Double) UnPrice * qtyInt;
                }
                else if(qty.equals("")){
                    Double disDou = Double.parseDouble(dis);
                    total = (Double) UnPrice * ((100 - disDou)/100);
                }

                else{
                    Integer qtyInt = Integer.parseInt(qty);
                    Double disDou = Double.parseDouble(dis);
                    total = (Double) UnPrice * qtyInt * ((100 - disDou)/100);
                }

                jLabel1.setText(Double.toString(total));

            }
            public void removeUpdate(DocumentEvent documentEvent) {

            }
        };

        Quantity_Input.getDocument().addDocumentListener(documentListener);
        Search_Button = new javax.swing.JButton();
        File = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Discount_Input = new javax.swing.JTextField();
        Discount_Input.getDocument().addDocumentListener(documentListener);
        Order_Status_Input = new javax.swing.JComboBox<>();
        AutoCompleteDecorator.decorate(Order_Status_Input);
        jLabel3 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Customer_Name_Input = new javax.swing.JComboBox<>();

        AutoCompleteDecorator.decorate(Customer_Name_Input);
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gold_database", "root" , "1234");
            PreparedStatement DBOUTPUT = conn.prepareStatement("SELECT name FROM customers");
            ResultSet RS = DBOUTPUT.executeQuery();	
            while(RS.next()){ 
                Customer_Name_Input.addItem(RS.getString("name"));
            }                                         
        }catch(Exception e) {
            System.out.println(e);
        }

        Customer_Name_Input.setSelectedIndex(-1);
        Customer_Name_Input.addItemListener(new ItemListener() {

            public void itemStateChanged(ItemEvent event) {

                if (event.getStateChange() == ItemEvent.SELECTED) {
                    String txt = Customer_Name_Input.getSelectedItem().toString();
                    try {
                        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gold_database", "root" , "1234");
                        PreparedStatement DBOUTPUT2 = conn.prepareStatement("SELECT address FROM customers WHERE name = ?");
                        DBOUTPUT2.setString(1, txt);
                        ResultSet RS2 = DBOUTPUT2.executeQuery();

                        if(RS2.next()) 
                        jLabel5.setText(RS2.getString("address"));
                    }catch(Exception e) {
                        System.out.println(e);
                    }
                }
            }
        });
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        Order_Date_Input = new org.jdesktop.swingx.JXDatePicker();
        Order_Due_Date_Input = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Product_ID_Input = new javax.swing.JComboBox<>();
        AutoCompleteDecorator.decorate(Product_ID_Input);

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gold_database", "root" , "1234");
            PreparedStatement DBOUTPUT3 = conn.prepareStatement("SELECT productID FROM products");
            ResultSet RS3 = DBOUTPUT3.executeQuery();
            while(RS3.next()){ 
                Product_ID_Input.addItem(RS3.getString("productID"));
            }
        }catch(Exception e) {
            System.out.println(e);
        }
        Product_ID_Input.setSelectedIndex(-1);

        Product_ID_Input.addItemListener(new ItemListener() {

            public void itemStateChanged(ItemEvent event) {

                if (event.getStateChange() == ItemEvent.SELECTED) {
                    String txt = Product_ID_Input.getSelectedItem().toString();
                    int product = Integer.parseInt(txt);    
                    try {
                        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gold_database", "root" , "1234");
                        PreparedStatement DBOUTPUT4 = conn.prepareStatement("SELECT price FROM products WHERE productID = ?");
                        DBOUTPUT4.setInt(1, product);
                        ResultSet RS4 = DBOUTPUT4.executeQuery();
                        String price = null;

                        if(RS4.next())
                        price = RS4.getString("price");

                        jLabel9.setText(price);

                        String qty = Quantity_Input.getText();
                        String dis = Discount_Input.getText();
                        Double UnPrice = Double.parseDouble(price);
                        Double total = null; 

                        if((qty.equals("")) && (dis.equals("")))
                        total = (Double) UnPrice;
                        else if(dis.equals("")){
                            Integer qtyInt = Integer.parseInt(qty);
                            total = (Double) UnPrice * qtyInt;
                        }
                        else if(qty.equals("")){
                            Double disDou = Double.parseDouble(dis);
                            total = (Double) UnPrice * ((100 - disDou)/100);
                        }

                        else{
                            Integer qtyInt = Integer.parseInt(qty);
                            Double disDou = Double.parseDouble(dis);
                            total = (Double) UnPrice * qtyInt * ((100 - disDou)/100);
                        }

                        jLabel1.setText(Double.toString(total));

                    }catch(Exception e) {
                        System.out.println(e);
                    }
                }
            }
        });
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gold_database", "root" , "1234");
            PreparedStatement DBOUTPUT5 = conn.prepareStatement("SELECT MAX(orderID) FROM orders");
            ResultSet RS5 = DBOUTPUT5.executeQuery();
            Integer num = null;

            if(RS5.next()){
                num =RS5.getInt(1);
            }
            if(num == 0){
                jLabel18.setText("1");
            }
            else{
                int number = num + 1;
                String n = Integer.toString(number);
                jLabel18.setText(n);
            }
        }catch(Exception e) {
            System.out.println(e);
        }
        Description = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Description_Input = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1220, 1010));

        Order_ID.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Order_ID.setText("Order ID");

        Customer_ID.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Customer_ID.setText("Customer Name");

        Product_ID.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Product_ID.setText("Product ID");

        Quantity.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Quantity.setText("Quantity");

        Order_Files.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Order_Files.setText("Order Files");

        Order_Status.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Order_Status.setText("Order Status");

        Discount.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Discount.setText("Discount");

        Total_Price.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Total_Price.setText("Total Price");

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel2.setText(":-");

        jLabel7.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel7.setText(":-");

        jLabel10.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        jLabel10.setText(":-");

        jLabel11.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel11.setText(":-");

        jLabel12.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel12.setText(":-");

        jLabel13.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel13.setText(":-");

        jLabel14.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel14.setText(":-");

        jLabel15.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel15.setText(":-");

        Quantity_Input.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Quantity_Input.setToolTipText("");

        Search_Button.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Search_Button.setText("Search");
        Search_Button.setPreferredSize(new java.awt.Dimension(153, 39));
        Search_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_ButtonActionPerformed(evt);
            }
        });

        File.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        File.setText("None Selected");

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel1.setText("0.0");

        Discount_Input.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N

        Order_Status_Input.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Order_Status_Input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No status", "Processing", "Packing", "Transport" }));

        jLabel3.setFont(new java.awt.Font("Matura MT Script Capitals", 3, 48)); // NOI18N
        jLabel3.setText("Order Form");

        Add.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Back.setText("Back");

        Customer_Name_Input.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel5.setText("No Customer selected");

        jButton6.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jButton6.setText("Add Customer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        Order_Date_Input.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Order_Date_Input.setPreferredSize(new java.awt.Dimension(160, 38));

        Order_Due_Date_Input.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Order_Due_Date_Input.setPreferredSize(new java.awt.Dimension(172, 38));

        jLabel6.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel6.setText("Order Date");

        jLabel8.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel8.setText("Due Date ");

        Product_ID_Input.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel9.setText("0.0");

        jLabel16.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel16.setText("Unit Price");

        jLabel17.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel17.setText(":-");

        jLabel18.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N

        Description.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Description.setText("Description");

        jLabel20.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel20.setText(":-");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(306, 126));

        Description_Input.setColumns(20);
        Description_Input.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        Description_Input.setRows(5);
        Description_Input.setPreferredSize(new java.awt.Dimension(303, 100));
        jScrollPane1.setViewportView(Description_Input);

        jLabel19.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel19.setText(":-");

        jLabel21.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel21.setText(":-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(453, 453, 453)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(438, 438, 438))
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel19)
                        .addGap(77, 77, 77)
                        .addComponent(Order_Date_Input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Order_Due_Date_Input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Order_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel20)
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(292, 292, 292))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(Product_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel10)
                        .addGap(79, 79, 79)
                        .addComponent(Product_ID_Input, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel11)
                        .addGap(77, 77, 77)
                        .addComponent(Quantity_Input))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(Order_Files, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel12)
                        .addGap(77, 77, 77)
                        .addComponent(File, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49)
                        .addComponent(Search_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(Order_Status)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel13)
                        .addGap(77, 77, 77)
                        .addComponent(Order_Status_Input, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(Discount, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel14)
                        .addGap(77, 77, 77)
                        .addComponent(Discount_Input))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(Total_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel15)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGap(212, 212, 212)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(Customer_ID)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7)
                        .addGap(77, 77, 77)
                        .addComponent(Customer_Name_Input, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(292, 292, 292))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Order_ID)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Description)
                    .addComponent(jLabel20)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(Order_Date_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Order_Due_Date_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Customer_Name_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Customer_ID)
                            .addComponent(jLabel7))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton6)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Product_ID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel10))
                    .addComponent(Product_ID_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Quantity_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Quantity)
                            .addComponent(jLabel11))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Search_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Order_Files)
                            .addComponent(jLabel12)
                            .addComponent(File))))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Order_Status_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Order_Status)
                            .addComponent(jLabel13))))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Discount)
                    .addComponent(jLabel14)
                    .addComponent(Discount_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Total_Price)
                    .addComponent(jLabel15)
                    .addComponent(jLabel1)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel9))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
    
    private void Search_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_ButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        File selectedFile = null;
        if (result == JFileChooser.APPROVE_OPTION) {
        selectedFile = fileChooser.getSelectedFile();
        File.setText(selectedFile.getAbsolutePath());
        }
              
    }//GEN-LAST:event_Search_ButtonActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        Integer orderID = Integer.parseInt(jLabel18.getText());
        String orderDes = Description_Input.getText();
        java.util.Date orderDate = Order_Date_Input.getDate();
        java.util.Date orderDueDate = Order_Due_Date_Input.getDate();
        String customerName = Customer_Name_Input.getSelectedItem().toString();
        String Address = jLabel5.getText();
        Integer productID = Integer.parseInt(Product_ID_Input.getSelectedItem().toString());
        String file = File.getText();
        String orderStatus = Order_Status_Input.getSelectedItem().toString();
        Double discount = Double.parseDouble(Discount_Input.getText());
        Double totalPrice = Double.parseDouble(jLabel1.getText());
        Double unitPrice = Double.parseDouble(jLabel9.getText());
               
         try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gold_database", "root" , "1234");
            
            FileInputStream fis = null;
            PreparedStatement DBOUTPUT6 = conn.prepareStatement("INSERT INTO orders VALUES(?,?,?,?,?,?,?,?,?,?,?,?)");
            DBOUTPUT6.setInt(1, orderID);
            DBOUTPUT6.setString(2, orderDes);
            
            java.sql.Date d1= new java.sql.Date(orderDate.getTime());
            DBOUTPUT6.setDate(3,d1);
            
            java.sql.Date d2= new java.sql.Date(orderDueDate.getTime());
            DBOUTPUT6.setDate(4,d2);
            
            DBOUTPUT6.setString(5, customerName);
            DBOUTPUT6.setString(6, Address);
            DBOUTPUT6.setInt(7, productID);
            
            File image= new File(file);
            fis = new FileInputStream(image);
            DBOUTPUT6.setBinaryStream(8, (InputStream) fis, (int) (image.length()));
            
            DBOUTPUT6.setString(9, orderStatus);
            DBOUTPUT6.setDouble(10, discount);
            DBOUTPUT6.setDouble(11, totalPrice);
            DBOUTPUT6.setDouble(12, unitPrice);
            
            DBOUTPUT6.executeUpdate();
            
        }catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_AddActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        Order_Date_Input.setDate(null);
        Order_Due_Date_Input.setDate(null);
        Customer_Name_Input.setSelectedIndex(-1);
        jLabel5.setText("No Customer selected");
        Product_ID_Input.setSelectedIndex(-1);
        Quantity_Input.setText("");
        File.setText("None Selected");
        Order_Status_Input.setSelectedIndex(-1);
        Discount_Input.setText("");
        jLabel1.setText("0.00");
        jLabel9.setText("0.00");        
             
        
    }//GEN-LAST:event_ResetActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            // Set cross-platform Java L&F (also called "Metal")
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
    } 
    catch (UnsupportedLookAndFeelException e) {
       // handle exception
    }
    catch (ClassNotFoundException e) {
       // handle exception
    }
    catch (InstantiationException e) {
       // handle exception
    }
    catch (IllegalAccessException e) {
       // handle exception
    }
         //Create and show the GUI.
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Back;
    private javax.swing.JLabel Customer_ID;
    private javax.swing.JComboBox<String> Customer_Name_Input;
    private javax.swing.JLabel Description;
    private javax.swing.JTextArea Description_Input;
    private javax.swing.JLabel Discount;
    private javax.swing.JTextField Discount_Input;
    private javax.swing.JLabel File;
    private org.jdesktop.swingx.JXDatePicker Order_Date_Input;
    private org.jdesktop.swingx.JXDatePicker Order_Due_Date_Input;
    private javax.swing.JLabel Order_Files;
    private javax.swing.JLabel Order_ID;
    private javax.swing.JLabel Order_Status;
    private javax.swing.JComboBox<String> Order_Status_Input;
    private javax.swing.JLabel Product_ID;
    private javax.swing.JComboBox<String> Product_ID_Input;
    private javax.swing.JLabel Quantity;
    private javax.swing.JTextField Quantity_Input;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Search_Button;
    private javax.swing.JLabel Total_Price;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
